// This file is auto-generated by bundle-token-types.js as a build step.
// Do not edit directly.

export const gleamSemanticTokenTypes = ["comment","constant","module","function","type","constructor","variable.parameter","variable","parameter","property","attribute","string","warning","string.escape","escape","function.builtin","builtin","number","error","comment.unused","unused","keyword","operator","punctuation.bracket","punctuation","bracket","punctuation.delimiter","delimiter"];
